### ISSUE TITLE
Remove container when execution finishes

### ISSUE THREAD

**Issue by matthewdu** [rwongone/testifi#63]
I noticed that I had hundreds of stopped containers. An auto remove flag should be passed here:
https://github.com/rwongone/testifi/blob/master/app/lib/test_executor.rb#L38

Not sure what the flag is though. Maybe @jchorl will know?

**Comment by rwongone** [comment]
Good find, I noticed this too. We may have to handle this in our own client. Maybe destroy the container at the end of our test execution job.

Docs do not specify a `--rm`-style option:
https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate

StackOverflow suggests that this is intentional.
https://github.com/docker/docker-py/issues/870

**Comment by rwongone** [comment]
Looks like I was mistaken: we were looking for a detail in `HostConfig` called `AutoRemove`.

**Comment by rwongone** [comment]
Tried setting AutoRemove using HostConfig:
```
opts = {
  ...
  'HostConfig' => {
    'AutoRemove' => true
  }
}
```
But this did not change the value of `AutoRemove` inside the container (upon performing a `docker inspect` of the created container). Nothing in the ruby docker-api client seems to explicitly prevent this, going to work around by calling `container.remove` once a test finishes executing.
